const Constant = {
  EMBED_URL: 'zf_embed=1&zf_embedwidgetvariant=micro&zf_embedstrictui=micro&zf_sendexternalappevent=1',
  TAG: 'zfTag',
  HTTPS: 'https://',
  URL: '.zonka.co/',
  RETROFIT_URL: '.zonkafeedback.com/api/v1/',
  SURVEY_CLOSE: 'zf-embed-submit-close',
  SURVEY_EXPAND: 'zf-embed-expand-widget',
  APP_VERSION_CODE: ' zf_sdk_app_version_code',
  DEVICE_RESOLUTION: ' zf_sdk_device_resolution',
  DEVICE_IMEI: ' zf_sdk_device_IMEI',
  DEVICE_SERIAL: ' zf_sdk_device_serial_number',
  GET_NETWORK: ' zf_sdk_network_type',
  DEVICE_NAME: ' zf_sdk_device_name',
  DEVICE_MODEL: ' zf_sdk_device_model',
  DEVICE_BRAND: ' zf_sdk_device_brand',
  TIME_ZONE: ' zf_sdk_timezone',
  ANDROID: 'Android',
  DEVICE_TYPE: 'zf_sdk_device_type',
  DEVICE_OS_VERSION: 'zf_sdk_os_version',
  APP_VERSION_NAME: 'zf_sdk_version',
  DEVICE_OS: 'zf_sdk_os',
  SCREEN_NAME: 'zf_sdk_screen',
  IS_WIDGET_ACTIVE: 'setIsWidgetActive',
  COMPANY_ID: 'companyId',
  SESSION_END_TIME: 'sessionEndTime',
  USER_FIRST_SEEN: 'user_first_seen',
  COOKIE_ID: 'cookieId',
  CONTACT_ID: 'contactId',
  EXTERNAL_VISITOR_ID: 'externalVisitorId',
  REQUEST_TYPE: 'requestType',
  FIRST_SEEN: 'firstSeen',
  LAST_SEEN: 'lastSeen',
  FIRST_SEEN_ON_ANDROID: 'firstSeenOnAndroid',
  LAST_SEEN_ON_ANDROID: 'lastSeenOnAndroid',
  IP_ADDRESS: 'ipAddress',
  DATE_FORMAT: 'yyyy-MM-dd HH:mm:ss',
  EMAIL_ID: 'contact_email',
  UNIQUE_ID: 'contact_uniqueId',
  MOBILE_NO: 'contact_mobile',
  CONTACT_NAME: 'contact_name',
  ZF_FUNCTION: 'ZonkaAppFunction',
  ZF_REGION: 'zfRegion',
  ZF_ANDROID: 'android',
  JOB_TYPE: 'jobType',
  UNIQUE_REF_CODE: 'uniqueRefCode',
  SDKTD: 'sdktd',
  CONTACT_DEVICE_OS: 'deviceOS',
  CONTACT_DEVICE_OS_VERSION: 'deviceOSVersion',
  CONTACT_DEVICE_NAME: 'deviceName',
  CONTACT_DEVICE_MODEL: 'deviceModel',
  CONTACT_DEVICE_BRAND: 'deviceBrand',
  CONTACT_DEVICE: 'device',
  CONTACT_LIST: 'contact_list',
  EXCLUDED_LIST: 'excluded_list',
  INCLUDED_LIST: 'included_list',
  EXCLUDE_TYPE: 'exclude_type',
  INCLUDE_TYPE: 'include_type',
  EVD_LIST: 'evd_list'
};
export default Constant;
export const CHECK_DELAY = 500;
//# sourceMappingURL=constant.js.map